ROS 2 Jazzyに対応します
rt-net/rt_manipulators_cpp pull request #34
Opened 2024-07-02 00:18 UTC by chama1176

# What does this implement/fix?

ROS 2 Jazzyに対応します

* Jazzyでビルドが通るように修正しました
  - 過去のバージョンでもCIでビルドが通ることは確認済みです
* CIにJazzyを追加しました
  - 合わせてどこかのバージョンでCIがコケてもCIを止めないようにMatrixの設定を変更しています

# Does this close any currently open issues?

いいえ

# How has this been tested?

CIでビルドが通ることを確認。
実機で動作確認予定

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-08-07 08:26 UTC, Kuwamai requested changes
ありがとうございます。
authorタグに名前の追加をお願いします。

https://github.com/rt-net/rt_manipulators_cpp/blob/feature/support-jazzy/rt_manipulators_examples/package.xml#L10

2024-08-08 01:14 UTC, chama1176 commented
@Kuwamai 
確認ありがとうございます
examplesの方は変更していないのでlibの方だけauthorタグに追加させていただきます（こちらも変更少しだけですが）

2024-08-08 01:17 UTC, chama1176 commented
追加して'rosdep install'のみ再確認しました

2024-08-09 04:44 UTC, Kuwamai approved these changes
LGTMです。

2024-08-09 04:45 UTC, merged